name: CI for ML Service

on:
  push:
    branches: [ main, dockerized-service, integrated-service ]
  pull_request:
    branches: [ main, dockerized-service, integrated-service ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/
